baseURL = 'https://alfredo.me/'
languageCode = 'en-us'
title = 'Alfredo.me'

copyright = "Copyright Â© 2025 Alfredo Gutierrez. All rights reserved."

theme = "dario"

[params]
  description = "Alfredo's personal blog"

  [params.author]
    name = "Alfredo Gutierrez"
    email = "alfredo@alfredo.me"
